# Generated by Django 5.2.5 on 2025-08-27 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_id', models.CharField(help_text='训练任务的唯一ID', max_length=36, unique=True)),
                ('status', models.CharField(choices=[('preparing', '准备中'), ('running', '运行中'), ('completed', '已完成'), ('error', '出错'), ('stopped', '已停止'), ('stopping', '停止中')], default='preparing', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('config', models.JSONField(help_text='训练配置参数')),
                ('current_epoch', models.IntegerField(default=0)),
                ('total_epochs', models.IntegerField(default=10)),
                ('progress', models.FloatField(default=0.0, help_text='训练进度百分比')),
                ('current_loss', models.FloatField(default=0.0)),
                ('current_accuracy', models.FloatField(default=0.0)),
                ('current_val_loss', models.FloatField(default=0.0)),
                ('epoch_losses', models.JSONField(default=list, help_text='每个epoch的训练损失')),
                ('epoch_accuracies', models.JSONField(default=list, help_text='每个epoch的验证准确率')),
                ('epoch_val_losses', models.JSONField(default=list, help_text='每个epoch的验证损失')),
                ('step_losses', models.JSONField(default=list, help_text='每100步的训练损失')),
                ('step_labels', models.JSONField(default=list, help_text='每100步的标签')),
                ('total_samples', models.IntegerField(default=0)),
                ('current_samples', models.IntegerField(default=0)),
                ('samples_per_epoch', models.IntegerField(default=0)),
                ('error_samples', models.JSONField(default=list, help_text='错误样本信息')),
                ('error_message', models.TextField(blank=True, null=True)),
                ('model_path', models.CharField(blank=True, max_length=255, null=True)),
                ('logs', models.JSONField(default=list, help_text='训练日志')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
